[phases.setup]
nixPkgs = ["python310", "tesseract", "leptonica"]
aptPkgs = ["tesseract-ocr-ind", "tesseract-ocr-eng"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
